### ISSUE TITLE
No longer works in Plex Web version 3.87.2

### ISSUE THREAD

**Issue by elelunicy** [Kayomani/PlexExternalPlayer#33]
It still works in my local Plex Web (version 3.77.4), but the version accessed through app.plex.tv/desktop# is now 3.87.2 and it no longer works.

**Comment by cremor** [comment]
I think it was broken before 3.87.2. Version 3.81.1 still worked without changes, but some later version introduced the problematic changes.

The change that broke the icons in the toolbar is that `plex-icon-toolbar-play-560` is now an id instead of a class.

The change that broke the icons on the posters was also a change from class to id, this time for `plex-icon-more-560`. But just changing the jQuery selector doesn't fix it in this case.

Note that this not only affects the hosted web app, but also newer server versions. Plex Media Server 1.15.1.707 updated the web app to 3.83.1, which might also be affected. Right now these newer server versions are only available as beta versions, but that will change eventually.

**Comment by Kayomani** [comment]
Tracked by #31
