### ISSUE TITLE
Plex URL is being returned as "undefined" when playing externally

### ISSUE THREAD

**Issue by jvlflame** [Kayomani/PlexExternalPlayer#50]
Just upgraded my userscript from v1.18 due to the issue of `Could not find authentication info`.
![image](https://user-images.githubusercontent.com/17932235/110227945-f9c9df80-7eb1-11eb-9b4e-98b1af4974b9.png)

After upgrading to v1.21, I'm receiving a new error. It seems that the server url is not being retrieved and is being returned as undefined.
![image](https://user-images.githubusercontent.com/17932235/110227868-79a37a00-7eb1-11eb-8560-dd2ea54a9e73.png)

I've tried to work around this error by hardcoding the correct url in parts of the script, but it is not functioning as expected. The error is not being returned anymore and the success popup is shown with the correct file path, but the video is not opening on my local system when clicking the "Play Externally" button. 

Not sure if this is an issue isolated to my setup or not, but any help would be appreciated. Thanks!

Agent: 1.12.0.0
Userscript: 1.21
Plex Media Server: 1.21.4.4079

**Comment by LuckyLuke-AT** [comment]
Are you using app.plex.tv or the servers own web interface?
Also what browser are you using?

For the looks of it, it seems that for some reason the script is not able to do the api call to Plex to get the list of known servers.
I think I had a similar issue in the past which was caused by the token not being available in the local storage in time. Normally this went away after simply refreshing the page once and after I added the 1s delay it has not been an issue anymore.

When you hardcoded the url, did you also take care about setting the serverId? 
To make troubleshooting a bit easier, please revert the script to it's original state and hardcode the server the following way:
Look for this section of the script
```
//Get known Plex Servers
var pmsUrls = new Map();
setTimeout(function () {
    getHosts();
    console.log(pmsUrls);
}, 1000);
```
comment out the setTimeout part and add your serverId + url to the map manually 

`pmsUrls.set('<serverId>','http://<host>:<port>')`
so that it looks something like this:
```
//Get known Plex Servers
var pmsUrls = new Map();
/*setTimeout(function () {
    getHosts();
    console.log(pmsUrls);
}, 1000);*/
pmsUrls.set('0987adf7adsf0a7dsf8a7sd0f78d','http://localhost:32400')
```
The server id is the part after /server/ in the url when you open a show or movie.

**Comment by jvlflame** [comment]
> Are you using app.plex.tv or the servers own web interface?

I'm only using my server's web interface, in this case `http://192.168.14.99:32400`.

> Also what browser are you using?

I was using Brave. I didn't think to try another browser at the time since this was working previously with 1.18. After testing with both Chrome and Firefox as well, the error with the `undefined` server url seems to persist. If it makes any difference, my PMS is running on docker with the linuxserver/plex image.

> comment out the setTimeout part and add your serverId + url to the map manually
> pmsUrls.set('<serverId>','http://\<host>:\<port>')

Awesome! This workaround is much easier than what I was working with previously.

~~So from what I can tell, my second issue of my video/directories not opening on my local system is isolated to using Brave browser. After trying the updated script on both Firefox and Chrome, it is working as expected. I'm looking at the [version diff](https://greasyfork.org/en/scripts/13437-plex-external-player/diff?v1=899951&v2=728667) between 1.18 and 1.21, but I'm not quite sure what may have changed to cause it to break on Brave. But at the very least we know that it's an issue with my browser. I've tried disabling Brave shields as well as disabling all browser extensions, but still no go.~~
Edit: So, after restarting my computer, strangely enough it is working on Brave now. Not sure why that fixed it, but I'm fine with that!

**Comment by LuckyLuke-AT** [comment]
Glad to hear that it's working for you now.

I'll try to look into the `undefined` server url issue next weekend, if I find the time for it. Not sure how how that will go, since it is working fine on my end.
Though I think I might be able to get rid of the api call and just use what is already available in the local storage of the browser.

**Comment by jvlflame** [comment]
I ended up testing it with the default script again just to see if I could do some additional troubleshooting on my side, and it seems like the error has resolved itself...

I'm not sure what was causing the server to be returned as `undefined`, and it was a persistent issue until now. I'll close this issue unless I find that it happens again. Thanks for your help!

**Comment by jvlflame** [comment]
Ok after some more testing, I found what the original issue is. When I'm connected to my VPN (PIA), the server is being returned as `undefined`. Turning off the VPN lets it work as expected.
